#!/usr/bin/env python3
"""Fetch the naked-eye Hipparcos catalog from CDS VizieR."""

from __future__ import annotations

import csv
import json
import pathlib
import urllib.parse
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data" / "hipparcos-stars.js"
SOURCE = "I/239/hip_main"
MAGNITUDE_LIMIT = 6.5
FIELDS = ("HIP", "RAICRS", "DEICRS", "Vmag", "B-V")


def catalog_url() -> str:
    query = urllib.parse.urlencode(
        {
            "-source": SOURCE,
            "-out": ",".join(FIELDS),
            "Vmag": f"<={MAGNITUDE_LIMIT}",
            "-out.max": "unlimited",
        }
    )
    return f"https://vizier.cds.unistra.fr/viz-bin/asu-tsv?{query}"


def fetch_rows() -> list[list[float | int | None]]:
    request = urllib.request.Request(
        catalog_url(), headers={"User-Agent": "SimSolar catalog generator"}
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        lines = response.read().decode("utf-8").splitlines()

    header_index = next(
        index for index, line in enumerate(lines) if line.startswith("HIP\t")
    )
    rows: list[list[float | int | None]] = []
    for fields in csv.reader(lines[header_index + 3 :], delimiter="\t"):
        if len(fields) != len(FIELDS):
            continue
        values = [field.strip() for field in fields]
        if not all(values[:4]):
            continue
        rows.append(
            [
                int(values[0]),
                round(float(values[1]), 7),
                round(float(values[2]), 7),
                round(float(values[3]), 2),
                round(float(values[4]), 3) if values[4] else None,
            ]
        )
    return rows


def main() -> None:
    stars = fetch_rows()
    payload = {
        "source": SOURCE,
        "sourceUrl": "https://cdsarc.cds.unistra.fr/viz-bin/Cat?I/239",
        "catalog": "ESA Hipparcos Main Catalogue",
        "coordinateFrame": "ICRS",
        "coordinateEpoch": "J1991.25",
        "magnitudeBand": "Johnson V",
        "magnitudeLimit": MAGNITUDE_LIMIT,
        "columns": ["HIP", "RA degrees", "Dec degrees", "Vmag", "B-V"],
        "stars": stars,
    }
    content = (
        "// Generated by tools/fetch-stars.py from CDS VizieR I/239/hip_main.\n"
        "window.HIPPARCOS_STAR_CATALOG="
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
    )
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {len(stars):,} stars to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
